### ISSUE TITLE
Error on 64 bit BitWidth in LLVM

### ISSUE THREAD

**Issue by Fare9** [pgarba/SiMBA-#2]
I've had an segmentation fault trying to run the tool for LLVM samples with a `BitWidth` of 64 bits, the error comes from the next line:

https://github.com/pgarba/SiMBA-/blob/21df900eb13a10844a937ad51862e0ca86453a5a/LLVMParser.cpp#L161

The value `Modulus` will obtain a value of 0, since it is a `uint64_t`. The value will be passed as parameter in the next call:

https://github.com/pgarba/SiMBA-/blob/21df900eb13a10844a937ad51862e0ca86453a5a/LLVMParser.cpp#L182

Inside of `initResultVector` the value `Modulus` is used in the next line:

https://github.com/pgarba/SiMBA-/blob/21df900eb13a10844a937ad51862e0ca86453a5a/LLVMParser.cpp#L104

And that generates a division by 0, causing a Segmentation Fault.

I have seen that in `Simplifier` class you use a `modulus` with a value of type `int64_t`, then the value of the call to `pow` will not generate a value of 0. Could be possible to change the `Modulus` variable from `LLVMParser.cpp` and the parameter of `initResultVector` from `uint64_t` to `int64_t`, for example like the next changes:

`LLVMParser.h`:

```cpp
void initResultVector(llvm::Function &F, std::vector<int64_t> &ResultVector,
                        int64_t Modulus, int VNumber, llvm::Type *IntType);
```

`LLVMParser.cpp`:

```cpp
int64_t Modulus = pow(2, this->BitWidth);

...

void LLVMParser::initResultVector(llvm::Function &F,
                                  std::vector<int64_t> &ResultVector,
                                  int64_t Modulus, int VNumber, Type *IntType) {
```

If that is a valid solution, let me know, and I will be happy to make a pull request.

The paper and the tool are amazing!

**Comment by pgarba** [comment]
Did you try to run the fix on the MBAs provided in the `data` folder once you converted them to LLVM IR ?

**Comment by Fare9** [comment]
I run first the python script to re-generate the .ll files:

```console
$ python3 convert_data_to_llvm.py 
Converting pldi_dataset_poly_MBA.txt to LLVM IR ...
   _____ __  ______  ___    __    __ 
  / __(_)  |/  / _ )/ _ |__/ /___/ /_
 _\ \/ / /|_/ / _  / __ /_  __/_  __/
/___/_/_/  /_/____/_/ |_|/_/   /_/1.0
°°SiMBA ported to C/C++/LLVM ~pgarba~
...
$ echo $?
0
```

And now if I run the test cases from the `README.md` with the fixes applied:

```cpp
$ ./SiMBA++ -ir ../llvm/e1_2vars.ll -optimize=true -fastcheck=false
   _____ __  ______  ___    __    __ 
  / __(_)  |/  / _ )/ _ |__/ /___/ /_
 _\ \/ / /|_/ / _  / __ /_  __/_  __/
/___/_/_/  /_/____/_/ |_|/_/   /_/1.0
°°SiMBA ported to C/C++/LLVM ~pgarba~

[+] Loading LLVM Module: '../llvm/e1_2vars.ll'
[+] Running LLVM optimizer ...		 Done! (337 ms)
[+] Simplifying 1000 functions ...	Done! (21 ms)
[+] MBAs: '1000' time: 22ms
$ ./SiMBA++ -ir ../llvm/e1_3vars.ll -optimize=true -fastcheck=false
   _____ __  ______  ___    __    __ 
  / __(_)  |/  / _ )/ _ |__/ /___/ /_
 _\ \/ / /|_/ / _  / __ /_  __/_  __/
/___/_/_/  /_/____/_/ |_|/_/   /_/1.0
°°SiMBA ported to C/C++/LLVM ~pgarba~

[+] Loading LLVM Module: '../llvm/e1_3vars.ll'
[+] Running LLVM optimizer ...		 Done! (749 ms)
[+] Simplifying 1000 functions ...	Done! (52 ms)
[+] MBAs: '1000' time: 53ms
$ ./SiMBA++ -ir ../llvm/test_data.ll -optimize=true -fastcheck=false
   _____ __  ______  ___    __    __ 
  / __(_)  |/  / _ )/ _ |__/ /___/ /_
 _\ \/ / /|_/ / _  / __ /_  __/_  __/
/___/_/_/  /_/____/_/ |_|/_/   /_/1.0
°°SiMBA ported to C/C++/LLVM ~pgarba~

[+] Loading LLVM Module: '../llvm/test_data.ll'
[+] Running LLVM optimizer ...		 Done! (6797 ms)
[+] Simplifying 10000 functions ...	Done! (721 ms)
[+] MBAs: '10000' time: 740ms
```

This time I do not get any error, when I try with the code without the changes, I obtain a `BitWidth` of 64, and when apply the `pow` in `Modulus` the value 0 is stored.

**Comment by pgarba** [comment]
ok, I'm not able to reproduce it but if the tests are ok then please create a pull request and I will merge it.

**Comment by Fare9** [comment]
Okay, I've found the source of the error, I'm having the issue when I use an older version from clang++ (for example clang++-12), and also with g++ (in this case g++-11 which is not so old), but I'm not having any error at all if I use clang++-15, maybe it's possible to give a recommended compiler in the README, and close the issue. Sorry for the mess on this...

**Comment by pgarba** [comment]
np, thats for looking into it. I will replace it with a table to avoid the problem
